FROM alpine:3.5

ENV PATH $PATH:/usr/local/avr/bin

RUN apk add --no-cache openssl bash git gcc g++ libc-dev gmp-dev mpfr-dev mpc1-dev make \
# Create build folder
&& NPROC=$(grep -c ^processor /proc/cpuinfo 2>/dev/null || 1) && mkdir /tmp/distr && cd /tmp/distr \
&& mkdir /dist 

ADD ./dist /dist

RUN cd /dist \

# Building cmake
#
&& tar -xvf cmake-3.9.3.tar.gz && cd cmake-3.9.3 \
&& ./bootstrap && make -j${NPROC} && make install && cd .. \
#
# Building binutils
#
&& bunzip2 -c binutils-2.28.tar.bz2 | tar xf - && cd binutils-2.28 \
&& mkdir build && cd build \
&& ../configure --prefix=/usr/local/avr --target=avr --disable-nls \
&& make -j${NPROC} && make install && cd ../.. \
#
# Build gcc
#
&& tar -xvf gcc-7.2.0.tar.xz && cd gcc-7.2.0 \
&& mkdir build && cd build \
&& ../configure --prefix=/usr/local/avr --target=avr --enable-languages=c,c++ --disable-nls --disable-libssp --with-dwarf2 \
&& make -j${NPROC} && make install && cd ../.. \
#
# Building avr-libc
#
&& bunzip2 -c avr-libc-2.0.0.tar.bz2 | tar xf - && cd avr-libc-2.0.0 \
&& ./configure --prefix=/usr/local/avr --build=`./config.guess` --host=avr \
&& make -j${NPROC} && make install && cd ../.. \
&& rm -rf /tmp/distr \
&& rm -rf /dist \
&& apk del openssl libc-dev gmp-dev mpfr-dev mpc1-dev 
